apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: prod-backend-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prod-backend
  template:
    metadata:
      labels:
        app: prod-backend
    spec:
      containers:
        - name: prod-backend
          image: simkids/prod-dealivery-backend:1.7
          #image: simkids/dealivery-backend:v2 <- 새로운 버전 배포 할 때
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
               name: prod-backend-configmap
  strategy:
    blueGreen:
      #activeService는 현재 운영중인 Blue 서비스
      activeService: prod-backend-service-active

      #previewService는 새롭게 배포될 Green 서비스
      previewService: prod-backend-service-preview
