kind: Service
apiVersion: v1
metadata:
  name: prod-frontend-service-active
spec:
  type: NodePort
  selector:
    app: prod-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30115