apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout-oauth
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: oauth2-proxy
  template:
    metadata:
      labels:
        name: oauth2-proxy
    spec:
      containers:
        - name: backend
          image: simkids/dealivery-backend:1.${LATEST_VERSION}
          #image: simkids/dealivery:v2 <- 새로운 버전 배포 할 때
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    blueGreen:
      #activeService는 현재 운영중인 Blue 서비스
      activeService: backend-service-oauth-active

      #previewService는 새롭게 배포될 Green 서비스
      previewService: backend-service-oauth-preview