kind: Service
apiVersion: v1
metadata:
  name: backend-service-active
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30101