name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 머지될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 프로젝트 빌드
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build project
      working-directory: backend  # backend 디렉토리로 이동
      run: |
        ./gradlew clean build

    # 3. EC2로 전송 및 배포
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_IP }}
      run: |
        # SSH 설정
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # 빌드된 파일 전송 (backend 디렉토리 내부의 build/libs)
        scp -o StrictHostKeyChecking=no backend/build/libs/*.jar $EC2_USER@$EC2_HOST:/home/ec2-user/app.jar

        # EC2에서 JAR 실행
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
        pkill -f 'java -jar' || true
        nohup java -jar /home/ec2-user/app.jar > /home/ec2-user/app.log 2>&1 &
        EOF
